### ISSUE TITLE
migrate-libs -> 2 versions of the same dependency

### ISSUE THREAD

**Issue by JavierMonton** [scalacenter/scala3-migrate#179]
First of all, thank you so much for this tool! I'll try to use it in a few repositories and give more feedback if I can.

When using `migrate-libs` I got a suggestion for 2 versions of the same dependency, I guess is an error, see attached image:
![imagen](https://user-images.githubusercontent.com/32640454/112344256-34aa8080-8cc4-11eb-9892-3f7841de3b7a.png)

**Comment by mlachkar** [comment]
Actually, it's not an error, but clearly, we can add a comment to explain why we propose more than one version! 

So for scalatest, there are multiple versions that are compatible with 3.0.0-RC1, and we decided to show the closest to the version you are using, and also the last available. It seems too confusing, Do you think it could be cleared with an additional comment "Multiple versions are published for 3.0.0-RC1".

**Comment by JavierMonton** [comment]
Oh, sorry then! I guess a comment can be useful, but in any case, I don't consider it a problem, while updating the dependency you'll add only one. 
Thanks for the clarification!
