### ISSUE TITLE
Option to not suggest 2.13 libraries

### ISSUE THREAD

**Issue by nafg** [scalacenter/scala3-migrate#181]
It is not recommended to publish a library for 3.0 that depends on a library for 2.13, since this can create diamond dependency conflicts. For applications it's fine though.

Either migrate-libs should be configurable to not suggest such changes, or else whenever it suggests a 2.13 replacement it should print the caveat.

**Comment by nafg** [comment]
(To be clear, I don't mean it should *omit* the notices, but rather not consider them an acceptable option, instead emitting an error.)

**Comment by mlachkar** [comment]
Thanks! I think it could be interesting to print the caveat at least.
