### ISSUE TITLE
Java library being flagged as containing macros

### ISSUE THREAD

**Issue by reibitto** [scalacenter/scala3-migrate#204]
I use SWT in a Scala project and noticed it's getting flagged as containing macros, which I can't imagine is correct considering it's a Java library. I'm not sure what about that library is causing this, but I thought I'd report this because the cause might flag other Java libraries for other people too.

![image](https://user-images.githubusercontent.com/6395394/115930268-1f439480-a4c4-11eb-8b0a-c52dd3da419c.png)

**Comment by mlachkar** [comment]
Hello, thanks for reporting this. It's definitely a bug! I will fix it soon

**Comment by mlachkar** [comment]
Hello, a new release has been published `0.4.4` that fixes this bug. If you have time to try and give some feedbacks, please do. Thanks again
