### ISSUE TITLE
Move to 3.0.0-RC3

### ISSUE THREAD

**Issue by DavidGoodenough** [scalacenter/scala3-migrate#216]
When I run scala3-migrate it says at the end that I can now upgrade to 3.0.0-RC2, but RC3 is out.  Also the library dependency stage for instance suggests moving to _2.13 versions of libraries for which there are RC3 but not RC2 versions.  An example being ScalaFX 16.0.0.0-R22 which supports RC3.

**Comment by mlachkar** [comment]
Hello!
I have updated scala3-migrate to RC3. I had troubles publishing on Friday, but now it's done!
You can now use `0.4.1`! Thanks for reporting this.
