### ISSUE TITLE
Publishing migrate-rules as a 2.12 artifact

### ISSUE THREAD

**Issue by daddykotex** [scalacenter/scala3-migrate#227]
Hi, thanks for the migration project, it's really useful.

It's my understanding that to run an external rule, you can't use the CLI and instead, you must use the sbt plugin. I've tried different syntax including, for example : `scalafix -r dependency:fix.scala213.Any2StringAdd@ch.epfl.scala:migrate-rules:0.4.2`, but none of them work.

So back in sbt I try to do:

```
sbt> scalafix dependency:fix.scala213.Any2StringAdd@ch.epfl.scala:migrate-rules:0.4.2
[error] (module1 / Compile / scalafix) scalafix.sbt.InvalidArgument: Failed to fetch [Dependency(Module(ch.epfl.scala, migrate-rules_2.12), 0.4.2)]from [...]
```

But it fails because it's looking for a 2.12 artifact. I do not have a problem with the migration-plugin itself, running `migrate-syntax project` works fine. But if I try to use the rules, individually, it fails.

I want to be able to run the rule individually because we have a pipeline to run scalafix for us, on a project, given a rule and open a PR when successful.

**Comment by daddykotex** [comment]
Oh well, it's my bad. You can use `scalafix` cli to run external rule (bundled in jars) as long as you put them on the class path.
The CLI has a `--tool-classpath` option. You can use `cs`  (coursier) to build that classpath for you.

Furthermore, the rules I want to run are published in https://github.com/scala/scala-rewrites rather than this project. You can find the artifact here: https://index.scala-lang.org/scala/scala-rewrites/scala-rewrites/0.1.3?target=_2.13

**Comment by daddykotex** [comment]
Other rules can be found here: https://index.scala-lang.org/ohze/scala-rewrites/scala-rewrites/1.0.0?target=_2.12

**Comment by mlachkar** [comment]
Sorry I didn't help, but I m happy you solved your issue! Thanks for the feedback
