### ISSUE TITLE
scala3-migrate may need a newer scalameta version

### ISSUE THREAD

**Issue by Bersier** [scalacenter/scala3-migrate#461]
When running `migrateSyntax`, I get the following error:
```
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.13:4.8.8
[error]   Not found
[error]   Not found
[error]   not found: /home/bersier/.ivy2/localorg.scalameta/semanticdb-scalac_2.13.13/4.8.8/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.13/4.8.8/semanticdb-scalac_2.13.13-4.8.8.pom
[error] Total time: 0 s, completed Mar 6, 2024, 10:46:38 AM
[error] Migration of root failed.
```
Scala version: 2.13.13
sbt version: 1.9.9

**Comment by SethTisue** [comment]
if anyone else hits this: I would think (without having actually tried it) that downgrading from Scala 2.13.13 to 2.13.12 before running scala3-migrate would work, as a workaround.

**Comment by adpi2** [comment]
> @adpi2 I guess I should add scala3-migrate to the "Prepare downstream: Open tickets in these repos, requesting publishing: ..." section of https://github.com/scala/scala-dev/blob/scala-dev/.github/ISSUE_TEMPLATE/release.md ?

Yeah, but this is rather an issue in sbt itself, since we depend on `semanticdbEnabled := true`. It's rather inconvenient that we have to re-publish all the tools that depend on semanticdb after each new Scala version. Maybe we should better back-publish the semanticdb plugin on new Scala versions. @tgodzik do you thing it would be feasible?

**Comment by tgodzik** [comment]
I usually do that for a couple of versions, but I would need to know what version to publish to. I can do 4.8.8 for now, but there might be always a version we are missing.

**Comment by tgodzik** [comment]
I published semanticdb 4.8.8 for Scala 2.13.13, but I think the solution here would be to keep semanticdb version explicitly and update it automatically (and we need someone merging the PRs)

**Comment by adpi2** [comment]
> I published semanticdb 4.8.8 for Scala 2.13.13, but I think the solution here would be to keep semanticdb version explicitly and update it automatically (and we need someone merging the PRs).

Good idea, I am going to automate that.

But I still think it is important to back publish Semanticdb on new Scala versions. We have a few tools that depend on Semanticdb, for instance Scalafix, and it would be better not to couple the Scala release with them. Also as a user, it's inconvenient if I have to update the Scalafix plugin, before I can update the Scala version.

> I usually do that for a couple of versions, but I would need to know what version to publish to. I can do 4.8.8 for now, but there might be always a version we are missing.

I would assume that all the tools use the latest semanticdb version.

**Comment by tgodzik** [comment]
> But I still think it is important to back publish Semanticdb on new Scala versions.

> I would assume that all the tools use the latest semanticdb version.


That would be ideal :sweat_smile: For now I usually check Metals and scalafix used versions plus latest. I will try to check the version here also if I can remember.

**Comment by adpi2** [comment]
> That would be ideal 😅 For now I usually check Metals and scalafix used versions plus latest. I will try to check the version here also if I can remember.

It is okay if you don't check the version here: I will try to keep it up-to-date.
